Vefb Changes
DiamondLightSource/atip pull request #32
Opened 2024-11-14 15:16 UTC by T-Nicholls

Mainly changes to get VEFB working against the virtac again after https://github.com/DiamondLightSource/pythonSoftIOC/pull/82 broke it

2025-03-21 16:32 UTC, T-Nicholls commented
Added a fix for a bug Phil found, also we should do a release of atip after this merges as there hasn't been one since 2022

2025-03-25 15:40 UTC, ptsOSL commented
> Added a fix for a bug Phil found, also we should do a release of atip after this merges as there hasn't been one since 2022

It probably makes sense to do the copier-template refactor first and make sure everything is still working with the latest python versions etc before doing the (major) release. We could also include the transition to using aioca in this release? Or maybe we do another release with this, im not sure.

Then if we want to add more features etc for diamond 2 then we can do a further release.

2025-04-25 17:22 UTC, T-Nicholls commented
Ready for review whenever you get a chance @MJGaughran

2025-04-25 17:54 UTC, MJGaughran requested changes

2025-04-25 17:54 UTC, MJGaughran commented on src/virtac/atip_ioc_entry.py
> +        help="Increase output and logging verbosity",
What is 'output verbosity'? I can only see a logging verbosity increase.

2025-04-25 17:54 UTC, MJGaughran commented on src/virtac/create_csv.py
> +        csv_writer.writerows([data[0]] + sorted(data[1:]))
I assume this is done to order the elements while preserving the column titles? You could either pass in the titles as an extra argument, or be more explicit in the code, e.g.

```suggestion
        column_titles = data[0]
        sorted_output = [column_titles] + sorted(data[1:])
        csv_writer.writerows(sorted_output)
```

2025-04-25 17:54 UTC, MJGaughran commented on docs/tutorials/virtac_example.md
> +## Command Line Options:
With the auto docs / sphinx setup that Phil is now using, is it possible to reference generated CLI docs instead?

Otherwise this will end up outdated very quickly.

2025-04-25 17:58 UTC, T-Nicholls commented on src/virtac/atip_ioc_entry.py
> +        help="Increase output and logging verbosity",
Yep it only does logging verbosity, I'll remove "output and"

2025-04-25 18:00 UTC, T-Nicholls commented on src/virtac/create_csv.py
> +        csv_writer.writerows([data[0]] + sorted(data[1:]))
Yes, I'll do something to make it clearer

2025-04-25 18:02 UTC, T-Nicholls commented on docs/tutorials/virtac_example.md
> +## Command Line Options:
Good idea, I'll look into it

2025-04-28 10:37 UTC, ptsOSL commented on docs/tutorials/virtac_example.md
> +## Command Line Options:
I expect this is possible, however currently there arent proper docstrings documenting the CLI, so there isnt anything to reference. Perhaps it would be better to make this change when updating the rest of the documentation on a seperate PR?

2025-04-28 10:39 UTC, ptsOSL commented on src/virtac/create_csv.py
> +    print("Creating feedback PVs CSV file.")
These should all be using logging.debug(), but as this is the case for probably all of the print statements, we can do this in a dedicated PR

2025-04-28 10:40 UTC, ptsOSL approved these changes

2025-04-28 12:07 UTC, MJGaughran commented on src/virtac/create_csv.py
> +    print("Creating feedback PVs CSV file.")
The purpose of these statements is to provide feedback to the user on progress, especially as these steps can take some time. The print statement is appropriate.

2025-04-28 12:08 UTC, MJGaughran commented on docs/tutorials/virtac_example.md
> +## Command Line Options:
That's fine by me.

2025-04-28 14:34 UTC, MJGaughran approved these changes

2025-04-30 09:22 UTC, merged